### ISSUE TITLE
Why should not use React.Fragment?

### ISSUE THREAD

**Issue by a-kalinin** [derzunov/redux-react-i18n#9]
Здравствуйте, 
I suggest to use `React.Fragment` instead wrapping text with `<span>`. As you said - span is not best way to add text. Since React got this method, it is more useful. Of course, for compatibility with previous versions, you can add check for React version, or Fragment availability, and fallback to `<span>`. What do you think? And if you don't have time I could make it, it won't take much time.

And some flood - thank you guys for your efforts =)

**Comment by derzunov** [comment]
Hi!

If you make it and send a PR I'll be glad to merge it :)
